// Code generated by protoc-gen-go-ascii. DO NOT EDIT.

package example

func (x *Hello) Ascii() string {
	return ` _   _        _  _
| | | |      | || |
| |_| |  ___ | || |  ___
|  _  | / _ \| || | / _ \
| | | ||  __/| || || (_) |
\_| |_/ \___||_||_| \___/
`
}
